# Jekyll Configuration File

# Site settings
title: winstreak
description: Basketball App
baseurl: "/winstreak" # Base URL for project site. Use an empty string ("") if it's a user/organization site.
url: "https://JamalBuiltIt.github.io" # Your GitHub Pages base URL

# Build settings
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - .github
  - README.md
  - package.json
  - yarn.lock

# Plugins
plugins:
  - jekyll-seo-tag # Optional: Add SEO plugin if required
  - jekyll-sitemap # Optional: Add sitemap plugin if needed
